title: "Andrej Istomin's Blog"
email: "andrej.istomin.ikeen@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  I'm going to put some thoughts inside this blog. Maybe it will be an articles
  about software development, tutorials, tips and tricks. Probably some live
  ideas. We will see :)
baseurl: ""
url: "http://aistomin.github.io/"
github_username: "aistomin"
facebook_username:  "andrej.istomin.3"
linkedin_url: "https://de.linkedin.com/in/andrej-istomin-51ba7530"
markdown: kramdown
copyright: "© 2015 Andrej Istomin"
year: "2015"